const fs = require('fs')
const path = require('path')
const chai = require('chai')
chai.Should()

const html = fs.readFileSync(path.join(__dirname, '../public/index.html'), 'utf8')
const css = fs.readFileSync(path.join(__dirname, '../public/app.css'), 'utf8')
const js = fs.readFileSync(path.join(__dirname, '../public/app.js'), 'utf8')
const pkg = require('../package.json')

describe('F9 control webapp', function () {
  it('is a standalone public webapp', function () {
    pkg.keywords.should.include('signalk-webapp')
    html.should.match(/app\.js/)
    html.should.match(/app\.css/)
  })

  it('PUTs v1 intent paths for live control', function () {
    js.should.match(/electrical\.displays\.brightness/)
    js.should.match(/electrical\.displays\.mode/)
    js.should.match(/electrical\.displays\.control/)
    js.should.match(/\/signalk\/v1\/api\/vessels\/self\//)
    js.should.match(/'off' \|\| value === 'auto' \|\| value === 'auto-learning'/)
    js.should.match(/\['off', 'Manual'\]/)
    js.should.match(/\['auto-learning', 'Learning'\]/)
    js.should.match(/recordActiveSunLux/)
    js.should.match(/liveEditable/)
    js.should.match(/mappingEditable/)
    js.should.match(/control !== 'auto'/)
    js.should.match(/ \+ ' lumen'/)
  })

  it('is phone-first with 48px hit targets', function () {
    html.should.match(/maximum-scale=1/)
    css.should.match(/--hit-size:\s*48px/)
    css.should.match(/min-height:\s*var\(--hit-size\)/)
    css.should.match(/min-width:\s*var\(--hit-size\)/)
    css.should.match(/touch-action:\s*manipulation/)
    css.should.match(/input\[type='range'\]/)
    css.should.match(/\.percent/)
  })

  it('follows the phone light/dark setting for chrome', function () {
    css.should.match(/prefers-color-scheme:\s*dark/)
    css.should.match(/color-scheme:\s*light dark/)
    js.should.not.match(/body\.classList\.toggle\('night'/)
  })

  it('shows native scale and hides undeclared palettes', function () {
    js.should.match(/percentText/)
    js.should.match(/quantize\(Number\(value\)\)/)
    js.should.match(/slider\.type = 'range'/)
    js.should.match(/0\.1/)
    js.should.match(/modes: \['night'\]/)
    js.should.match(/navico/)
    js.should.match(/raymarine/)
    js.should.not.match(/garmin/)
  })

  it('has Day, Night, and Off glass buttons', function () {
    js.should.match(/\['off', 'Off'\]/)
    js.should.match(/put\(INTENT\.brightness, 0\)/)
    js.should.match(/put\(INTENT\.brightness, 0\.1\)/)
  })

  it('shows Time, Sun, and Lux mapping tables', function () {
    html.should.match(/id="mapping"/)
    html.should.match(/id="time-body"/)
    html.should.match(/id="sun-body"/)
    html.should.match(/id="lux-body"/)
    html.should.match(/id="lux-add"/)
    html.should.match(/id="native-day-body"/)
    html.should.match(/id="native-night-body"/)
    html.should.match(/<th>Brightness<\/th>/)
    html.should.not.match(/<th>Intent<\/th>/)
    html.should.match(/Brightness to B&amp;G and Raymarine/)
    html.should.match(/<th>B&amp;G color<\/th>/)
    html.should.match(/<th>Raymarine color<\/th>/)
    html.should.not.match(/Brand brightness[\s\S]*<th>Mode<\/th>/)
    html.should.match(/native-pair/)
    html.should.not.match(/<h3>Day<\/h3>[\s\S]*<th>B&amp;G color<\/th>[\s\S]*id="native-day-body"/)
    html.should.match(/<h3>Night<\/h3>[\s\S]*<th>B&amp;G color<\/th>/)
    html.should.match(/<th>B&amp;G brightness<\/th>\s*<th>B&amp;G color<\/th>/)
    html.should.match(/id="live-lux"/)
    html.should.match(/id="live-sun"/)
    html.should.match(/id="live-time"/)
    html.should.match(/live-now">\(<span id="live-time"/)
    html.should.match(/live-now">\(<span id="live-sun"/)
    html.should.match(/live-lux-wrap" class="live-now">\(<span id="live-lux"/)
    html.should.not.match(/id="live-sources"/)
    html.should.match(/lux-missing/)
    css.should.match(/min-width:\s*900px/)
    css.should.match(/#mapping\s*\{[^}]*display:\s*none/)
    css.should.match(/#mapping\.no-lux/)
    js.should.match(/if \(live\) \{/)
    js.should.match(/subscribeWs\(\)/)
    js.should.match(/seedDemo\(\)/)
    js.should.match(/native: nativeRows/)
    js.should.match(/palettes: mappingPalettes/)
    js.should.match(/Select for all/)
    js.should.match(/native-day-body/)
    js.should.match(/native-night-body/)
    css.should.match(/native-pair/)
    css.should.not.match(/native-head-night/)
    js.should.match(/lux-add/)
    js.should.match(/environment\.sun/)
    js.should.match(/environment\.mode/)
    js.should.match(/environment\.outside\.lux/)
    js.should.match(/hasLux/)
  })
})
